name: Custom container
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node18.12.0-chrome106-ff106
    name: Tests inside custom image
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: true
          group: Tests on Chrome
          env: lastName=Smith
        env:
          CYPRESS_firstName: Joe
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
